// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuobemgckdcqponviyjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1b2JlbWdja2RjcXBvbnZpeWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzgxNDYsImV4cCI6MjA1ODQxNDE0Nn0.gZxDM26HF-1AuXNTwSapo3U_bCndbJmMgmFtV8lmCUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);